### ISSUE TITLE
Moment error

### ISSUE THREAD

**Issue by VictorAlmeidaFonseca** [kielkow/template_vtex#3]
Hi!

I've got some issue at moment api that happend when trying use the sample one: const orderList = await vtex.Order.paginateLists(params);

const params = {
    "start": {
        "date": "26/06/2020"
   },
   "end": {
       "date" : "09/12/2020"
   }     
};
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 26/06/2020, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/home/linkapi/lkp/exces/node_modules/moment/moment.js:319:25)
    at configFromString (/home/linkapi/lkp/exces/node_modules/moment/moment.js:2536:19)
    at configFromInput (/home/linkapi/lkp/exces/node_modules/moment/moment.js:2977:13)
    at prepareConfig (/home/linkapi/lkp/exces/node_modules/moment/moment.js:2960:13)
    at createFromConfig (/home/linkapi/lkp/exces/node_modules/moment/moment.js:2927:44)
    at createLocalOrUTC (/home/linkapi/lkp/exces/node_modules/moment/moment.js:3021:16)
    at createLocal (/home/linkapi/lkp/exces/node_modules/moment/moment.js:3025:16)
    at hooks (/home/linkapi/lkp/exces/node_modules/moment/moment.js:16:29)
    at /home/linkapi/lkp/exces/node_modules/template-vtex/src/modules/orders-api/order/index.js:51:35
    at Array.forEach (<anonymous>)
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Order.paginateLists (/home/linkapi/lkp/exces/node_modules/template-vtex/src/modules/orders-api/order/index.js:71:47)
    at allOrders (/home/linkapi/lkp/exces/utils.js:37:37)
    at getDetails (/home/linkapi/lkp/exces/utils.js:58:30)
    at test (/home/linkapi/lkp/exces/utils.js:78:26)
    at Object.<anonymous> (/home/linkapi/lkp/exces/utils.js:80:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14) 
```

**Comment by VictorAlmeidaFonseca** [comment]
I nedded to pass TZ  to  work:

const params = {
    "start": {
        "date": "2020-06-28T22:08:20.403Z"
   },
   "end": {
       "date" : "2020-12-09T22:08:20.405Z"
   }     
};
